### ISSUE TITLE
Example never ends because of some deequ's alive thread

### ISSUE THREAD

**Issue by frbattid** [awslabs/python-deequ#72]
**Describe the bug**
Running the [example](https://github.com/awslabs/python-deequ#constraint-verification) never ends. It correctly shows the check results, but the application never ends because of some deequ's alive thread. Upon crtl+c, the following message appears:

```
^CException ignored in: <module 'threading' from '/usr/lib64/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib64/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib64/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/context.py", line 256, in signal_handler
KeyboardInterrupt: 
```

**To Reproduce**
Just run the following code, as described [here](https://github.com/awslabs/python-deequ#constraint-verification):

```
from pyspark.sql import SparkSession, Row
import pydeequ

spark = (SparkSession
    .builder
    .config("spark.jars.packages", pydeequ.deequ_maven_coord)
    .config("spark.jars.excludes", pydeequ.f2j_maven_coord)
    .getOrCreate())

df = spark.sparkContext.parallelize([
            Row(a="foo", b=1, c=5),
            Row(a="bar", b=2, c=6),
            Row(a="baz", b=3, c=None)]).toDF()

from pydeequ.checks import *
from pydeequ.verification import *

check = Check(spark, CheckLevel.Warning, "Review Check")

checkResult = VerificationSuite(spark) \
    .onData(df) \
    .addCheck(
        check.hasSize(lambda x: x >= 3) \
        .hasMin("b", lambda x: x == 0) \
        .isComplete("c")  \
        .isUnique("a")  \
        .isContainedIn("a", ["foo", "bar", "baz"]) \
        .isNonNegative("b")) \
    .run()

checkResult_df = VerificationResult.checkResultsAsDataFrame(spark, checkResult)
checkResult_df.show()
```

Command used to run it:

    $ SPARK_VERSION=2.3 PYSPARK_PYTHON=/usr/bin/python3.6 spark-submit --master yarn --deploy-mode client --packages com.amazon.deequ:deequ:1.0.5 --exclude-packages net.sourceforge.f2j:arpack_combined_all pydeequ-test.py

**Expected behavior**
The application example ends.

**Infrastructure**
 - Spark 2.3
 - Python 3.6
 - [deequ 1.0.5](https://mvnrepository.com/artifact/com.amazon.deequ/deequ/1.0.5) (but the same behaviour is shown for other versions)
 - [pydeequ 1.0.1](https://pypi.org/project/pydeequ/)

**Comment by poolis** [comment]
I was having a similar issue.  I added this and it seemed to make the process exit smoothly:
`spark.sparkContext._gateway.shutdown_callback_server()`

**Comment by frbattid** [comment]
Ho @poolis , it works like a charm. Many many thanks!
