### ISSUE TITLE
Deequ error for Uniqueness analyzer (iterableAsScalaIterable)

### ISSUE THREAD

**Issue by Shijin1387** [awslabs/python-deequ#73]
Describe the bug
Trying few example from pydeequ quickstart. When trying to compute Uniqueness facing java exception 'Method iterableAsScalaIterable([class java.lang.String]) does not exist'

To Reproduce
Steps to reproduce the behaviour:

Start Jupyter from Pyspark shell
All examples from basic tutorial works however adding analyser .addAnalyzer(Uniqueness("b")) 
Brings the error. (screenshots attached).
Screenshots
![image](https://user-images.githubusercontent.com/43914423/132203050-b36b4c3b-4be9-46a3-b70d-4dca2dceef06.png)

This is working
![image](https://user-images.githubusercontent.com/43914423/132203098-be22decc-f1c3-45da-ab7e-8ddc08ee543c.png)
 **This is not working** 
![image](https://user-images.githubusercontent.com/43914423/132203153-0b790ab7-2d1f-4895-978e-4603679e1f8b.png)

**Error:**
Py4JError: An error occurred while calling z:scala.collection.JavaConversions.iterableAsScalaIterable. Trace:
py4j.Py4JException: Method iterableAsScalaIterable([class java.lang.String]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:339)
	at py4j.Gateway.invoke(Gateway.java:276)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

Additional context
I have downloaded the deequ jar deequ-1.1.0_spark-3.0-scala-2.12.jar

**Comment by JonatanPolanco** [comment]
Same error here! and no idea how to fix it

**Comment by TPOTD** [comment]
@JonatanPolanco If you still need help, Uniqueness takes a list of columns (took it from documentation), so try ['column_name'] instead of just 'column_name'. It worked for me
![image](https://user-images.githubusercontent.com/62710736/160918944-64b1bbbb-fb51-4871-9e12-09a76b5293e6.png)
